### ISSUE TITLE
Built Plugin isn't visible in fledge

### ISSUE THREAD

**Issue by muslui** [fledge-iot/fledge-south-iec104#25]
Hello,
I followed instructions and, after building I copied libiec104.so and libiec104.so.1 in /usr/local/fledge/plugins/south/iec104 as I found in documentation.
I tried to start service launching 
curl -sX POST http://localhost:8081/fledge/service -d '{"name":"iec104_name","type":"south","plugin":"iec104","enabled":true}'
but the following errore came out:
404: Plugin "iec104" import problem from path usr/local/fledge/python/fledge/plugins/south/iec104"
In which part of procedure I failed?
thank you.

**Comment by praveen-garg** [comment]
By any chance, you have copied to  /usr/local/fledge/python/fledge/plugins/south/ as well? 

Can you please share the output of: 

`ls -ltra /usr/local/fledge/python/fledge/plugins/south/` and 
`ls -ltra /usr/local/fledge/plugins/south/iec104` 

Also please check and share the response of  `curl  http://localhost:8081/fledge/plugins/installed`

**Comment by muslui** [comment]
I didn't copied to ls -ltra /usr/local/fledge/plugins/south/iec104

ls -ltra /usr/local/fledge/python/fledge/plugins/south/
total 12
-rw-r--r-- 1 root root    0 nov 29 16:36 __init__.py
drwxr-xr-x 7 root root 4096 nov 29 16:36 ..
drwxr-xr-x 2 root root 4096 dic 14 18:11 coap
drwxr-xr-x 3 root root 4096 dic 14 18:11 .

ls -ltra /usr/local/fledge/plugins/south/iec104
total 272
drwxr-xr-x 3 root root   4096 dic 16 11:53 ..
-rw-r--r-- 1 root root 269984 gen 20 18:00 libiec104.so.1
lrwxrwxrwx 1 root root     14 gen 20 18:01 libiec104.so -> libiec104.so.1
drwxr-xr-x 2 root root   4096 gen 20 18:01 .

**Comment by praveen-garg** [comment]
As requested in the previous comment,

> Also please check and share the response of  curl  http://localhost:8081/fledge/plugins/installed

**Comment by muslui** [comment]
sorry, 
I didn't copied last result:
curl http://localhost:8081/fledge/plugins/installed
{"plugins": [{"name": "OMF", "type": "north", "description": "PI Server North C Plugin", "version": "2.0.1", "installedDirectory": "north/OMF", "packageName": ""}, {"name": "coap", "type": "south", "description": "CoAP Listener South Plugin", "version": "2.0.1", "installedDirectory": "south/coap", "packageName": "fledge-south-coap"}]}

**Comment by muslui** [comment]
Dears,
we made some tests and, probably, there is an error trying to find the file iblib60870.so.2.3.1
we tried to copy this file in /usr/local/fledge/python/fledge/plugins/south/ without success.

**Comment by praveen-garg** [comment]
That is not the correct place to put in the linked shared lib. You should ensure correct permissions and put that in the correct place, checking path with `ldd` to iec libs. 

`ldd /usr/local/fledge/plugins/south/iec104/libiec104.so`

**Comment by muslui** [comment]
hello,
following all instructions the right position for the liblib60870.so.2.3.1 was /usr/local/lib
thank you.
